apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-app-config
data:
  # ------------------------------------------------------------------------------
  # app
  # ------------------------------------------------------------------------------

  APP_NAME: laravel
  APP_ENV: local
  APP_DEBUG: "true"
  APP_URL: https://myproject-local.com
  #APP_KEY:

  # NOTE: to use stern
  LOG_CHANNEL: errorlog

  # ------------------------------------------------------------------------------
  # DB
  # ------------------------------------------------------------------------------

  DB_HOST: mysql
  DB_USERNAME: root
  DB_PASSWORD: root

  DB_CONNECTION: mysql
  DB_DATABASE: sample
  DB_DATABASE_TEST: sample_test

  REDIS_HOST: redis-master

  # ------------------------------------------------------------------------------
  # MAIL
  # ------------------------------------------------------------------------------

  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: "2525"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_ENCRYPTION: "null"